---
- name: create includes directory
  file:
    path: "{{ monit_includes }}"
    state: directory
    mode: 0755

- name: create monit state directory
  become: yes
  file:
    path: "{{ monit_state_file | dirname }}"
    state: directory
    mode: 0755

- name: create monit id directory
  become: yes
  file:
    path: "{{ monit_id_file | dirname }}"
    state: directory
    mode: 0755

- name: config - Setup monitrc
  become: yes
  template:
    src: monitrc.j2
    dest: "{{ monitrc_conf }}"
    owner: root
    group: wheel
    mode: 0700
  notify: restart monit

- name: config - Setup LaunchDaemons plit
  become: yes
  template:
    src: com.mmonit.monit.plist.j2
    dest: "{{ launchdaemons_plist }}/com.mmonit.monit.plist"
    owner: root
    group: wheel
    mode: 0644
  notify: restart monit

- name: config - Setup mail alerts
  become: yes
  template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: root
    group: wheel
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled

- name: config - Setup webinterface
  become: yes
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: root
    group: wheel
    mode: 0644
  notify: restart monit

