---
- name: monitors - Create facts directory
  become: yes
  file:
    path: "{{ monit_facts_d }}"
    state: directory
    mode: 0755

- name: monitors - Registers configured monitors
  become: yes
  template:
    src: monit.fact.j2
    dest: "{{ monit_facts_d }}/monit.fact"
    mode: 0644
  register: monit_write_facts

- name: monitors - Reload facts
  setup:
    fact_path: "{{ monit_facts_d }}"
    filter: "ansible_local"
  when: monit_write_facts.changed

- name: monitors - List configured monitors
  command: ls -1 {{ monit_includes }}
  register: monit_services_present
  changed_when: false

- name: monitors - Remove unused monitors
  file:
    path: "{{ monit_includes }}/{{ item }}"
    state: absent
  with_items: monit_services_present.stdout_lines
  when: monit_service_delete_unlisted and item|basename not in ansible_local.monit.monit_configured_services
  notify: restart monit

