---
- name: config - Setup mail alerts
  become: yes
  template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: root
    group: wheel
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled

- name: config - Setup webinterface
  become: yes
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: root
    group: wheel
    mode: 0644
  notify: restart monit

- name: monitors - Write monitors
  become: yes
  template:
    src: monitor.j2
    dest: "{{ monit_includes }}/{{ item.name }}"
    owner: root
    group: wheel
  with_items: "{{ monit_services }}"
  notify: restart monit

